services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: aadk
    volumes:
      - data:/var/lib/postgresql/data
    network_mode: host

  back-end:
    build: back-end/BackEnd
    container_name: back-end
    network_mode: host

  front-end:
    build: front-end
    container_name: front-end
    network_mode: host

volumes:
  data:
