services:
  postgres:
    container_name: postgres
    image: postgres:latest
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_PASSWORD: aadk
    volumes:
      - data:/var/lib/postgresql/data
    network_mode: host

  back-end:
    build: back-end/BackEnd
    container_name: back-end
    network_mode: host
    depends_on:
      postgres:
        condition: service_healthy

  front-end:
    build: front-end
    container_name: front-end
    network_mode: host

volumes:
  data:
