services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: aadk
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - my-network

  back-end:
    build: back-end/BackEnd
    container_name: back-end
    ports:
      - "5000:5000"
    networks:
      - my-network
    environment:
      ConnectionStrings__Postgres: "Host=postgres;Port=5432;Database=CounterDatabase;Username=postgres;Password=aadk"

  front-end:
    build: front-end
    container_name: front-end
    ports:
      - "3000:3000"
    networks:
      - my-network

volumes:
  data:

networks:
  my-network:
